# Generated by Django 4.2.14 on 2024-09-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmuebleria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
